# Generated by Django 5.0.7 on 2024-07-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='A creamy pasta dish with chicken.', max_length=500),
            preserve_default=False,
        ),
    ]
